# Generated by Django 4.2 on 2023-11-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('latitude', models.TextField()),
                ('longtitude', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cuisine_id', models.ManyToManyField(to='logic.cuisine')),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='logic.location')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logic.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('delivery_cost', models.IntegerField()),
                ('service_cost', models.IntegerField()),
                ('resource_url', models.TextField()),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logic.promotion')),
                ('restaurant_id', models.ManyToManyField(to='logic.restaurant')),
            ],
        ),
    ]
