# Generated by Django 4.2 on 2023-11-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_alter_restaurant_promotion_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
    ]
