# Generated by Django 4.2 on 2023-11-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisines'},
        ),
        migrations.AlterModelOptions(
            name='deliverypicker',
            options={'verbose_name': 'DeliveryPicker', 'verbose_name_plural': 'DeliveryPickers'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
    ]
